# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  host: http://www.simpedilmongolia.mn/
  meta_title: SIMPEDIL MONGOLIA
  meta_description: SIMPEDIL MONGOLIA барилгын тоног төхөөрөмжийн худалдаа түрээс зээл лийзинг, construction equipments trade rent and leasing
  meta_keywords: SIMPEDIL MONGOLIA барилгын тоног төхөөрөмжийн худалдаа түрээс зээл лийзинг, construction equipments trade rent and leasing
  pager: 10

  phone: 99052507, 99031556
  email: martino_ikhee@yahoo.com
  address: Амгалан, М-Си-Эс Тiger үйлдвэрээс цааш 500 метрт<br>Улиастайн гүүрний наана "ЕВРО БАРИЛГА" худалдааны төв<br>Улаанбаатар хот, Монгол улс
  address_en: Amgalan, 500 metres from MCS Тiger Factory<br>"EURO CONSTRACTION" trade center beside the Bridge of Uliastai<br>Ulaanbaatar, Mongolia
  order_email: info@simpedilmongolia.mn
  facebook: simpedilmongolia
  twitter: Simpedil_Mongol
  youtube: user/martinoyou2be
  skype: simpedilmongolia
  yahoo: simpedilmongolia
  lat: 47.9029
  lng: 107.029
  invoice_email: sales@simpedilmongolia.mn