<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Spec', 'doctrine');

/**
 * BaseSpec
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $name_en
 * @property integer $sort
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $ProductSpec
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getNameEn()      Returns the current record's "name_en" value
 * @method integer             getSort()        Returns the current record's "sort" value
 * @method timestamp           getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()   Returns the current record's "updated_at" value
 * @method Doctrine_Collection getProductSpec() Returns the current record's "ProductSpec" collection
 * @method Spec                setId()          Sets the current record's "id" value
 * @method Spec                setName()        Sets the current record's "name" value
 * @method Spec                setNameEn()      Sets the current record's "name_en" value
 * @method Spec                setSort()        Sets the current record's "sort" value
 * @method Spec                setCreatedAt()   Sets the current record's "created_at" value
 * @method Spec                setUpdatedAt()   Sets the current record's "updated_at" value
 * @method Spec                setProductSpec() Sets the current record's "ProductSpec" collection
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSpec extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('spec');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('name_en', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('sort', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ProductSpec', array(
             'local' => 'id',
             'foreign' => 'spec_id'));
    }
}