<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Content', 'doctrine');

/**
 * BaseContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $title_en
 * @property string $image
 * @property string $body
 * @property string $body_en
 * @property boolean $is_active
 * @property boolean $is_featuired
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * 
 * @method integer   getId()           Returns the current record's "id" value
 * @method string    getTitle()        Returns the current record's "title" value
 * @method string    getTitleEn()      Returns the current record's "title_en" value
 * @method string    getImage()        Returns the current record's "image" value
 * @method string    getBody()         Returns the current record's "body" value
 * @method string    getBodyEn()       Returns the current record's "body_en" value
 * @method boolean   getIsActive()     Returns the current record's "is_active" value
 * @method boolean   getIsFeatuired()  Returns the current record's "is_featuired" value
 * @method timestamp getCreatedAt()    Returns the current record's "created_at" value
 * @method timestamp getUpdatedAt()    Returns the current record's "updated_at" value
 * @method Content   setId()           Sets the current record's "id" value
 * @method Content   setTitle()        Sets the current record's "title" value
 * @method Content   setTitleEn()      Sets the current record's "title_en" value
 * @method Content   setImage()        Sets the current record's "image" value
 * @method Content   setBody()         Sets the current record's "body" value
 * @method Content   setBodyEn()       Sets the current record's "body_en" value
 * @method Content   setIsActive()     Sets the current record's "is_active" value
 * @method Content   setIsFeatuired()  Sets the current record's "is_featuired" value
 * @method Content   setCreatedAt()    Sets the current record's "created_at" value
 * @method Content   setUpdatedAt()    Sets the current record's "updated_at" value
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('content');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('title_en', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('body_en', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('is_featuired', 'boolean', null, array(
             'type' => 'boolean',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}