<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PollOption', 'doctrine');

/**
 * BasePollOption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $poll_id
 * @property string $text
 * @property string $text_en
 * @property string $text_ru
 * @property integer $number
 * @property integer $sort
 * @property Poll $Poll
 * 
 * @method integer    getId()      Returns the current record's "id" value
 * @method integer    getPollId()  Returns the current record's "poll_id" value
 * @method string     getText()    Returns the current record's "text" value
 * @method string     getTextEn()  Returns the current record's "text_en" value
 * @method string     getTextRu()  Returns the current record's "text_ru" value
 * @method integer    getNumber()  Returns the current record's "number" value
 * @method integer    getSort()    Returns the current record's "sort" value
 * @method Poll       getPoll()    Returns the current record's "Poll" value
 * @method PollOption setId()      Sets the current record's "id" value
 * @method PollOption setPollId()  Sets the current record's "poll_id" value
 * @method PollOption setText()    Sets the current record's "text" value
 * @method PollOption setTextEn()  Sets the current record's "text_en" value
 * @method PollOption setTextRu()  Sets the current record's "text_ru" value
 * @method PollOption setNumber()  Sets the current record's "number" value
 * @method PollOption setSort()    Sets the current record's "sort" value
 * @method PollOption setPoll()    Sets the current record's "Poll" value
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePollOption extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poll_option');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('poll_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('text', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('text_en', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('text_ru', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('number', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sort', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Poll', array(
             'local' => 'poll_id',
             'foreign' => 'id'));
    }
}