<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Subscriber', 'doctrine');

/**
 * BaseSubscriber
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $email
 * @property timestamp $created_at
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method string     getEmail()      Returns the current record's "email" value
 * @method timestamp  getCreatedAt()  Returns the current record's "created_at" value
 * @method Subscriber setId()         Sets the current record's "id" value
 * @method Subscriber setEmail()      Sets the current record's "email" value
 * @method Subscriber setCreatedAt()  Sets the current record's "created_at" value
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubscriber extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subscriber');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}