<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }
    
    public function fetchall($params = array())
    {
        $q = Doctrine_Query::create()
            ->select('*')
            ->from('Category')
            ->orderBy('sort DESC');
  
            // KEYWORD
            if(isset($params['keyword']) && $params['keyword'])
              $q->andWhere('name LIKE ?', array('%'.$params['keyword'].'%'));
  
            // LIMIT
            $limit = isset($params['limit']) ? $params['limit'] : 100;
            $q->limit($limit);
    
        return $q->execute();
    }
}