<?php

/**
 * CommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Comment');
    }
    
    
    public function getPager($objectType, $objectId, $page=1)
    {
        $q = Doctrine_Query::create()
              ->select('*')
              ->from('Comment')
              ->where('object_type=? AND object_id=?', array($objectType, $objectId))
              ->orderBy('created_at ASC');
              
        $pager = new sfDoctrinePager('Comment', sfConfig::get('app_pager', 30));
        $pager->setPage($page);
        $pager->setQuery($q);
        $pager->init();
        
        return $pager;
    }
    
    public function fetchall($objectType, $objectId)
    {
      $q = Doctrine_Query::create()
              ->select('*')
              ->from('Comment')
              ->where('object_type=? AND object_id=?', array($objectType, $objectId))
              ->orderBy('created_at ASC');
      return $q->execute();
    }
    
    public function fetchone($ipAddress, $objectType, $objectId, $body)
    {
      $q = Doctrine_Query::create()
              ->select('*')
              ->from('Comment')
              ->where('ip_address=? AND object_type=? AND object_id=? AND text=?', array($ipAddress, $objectType, $objectId, $body));
      return $q->fetchOne();
    }
}