<?php

/**
 * Comment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    grand
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Comment extends BaseComment
{
  public function __toString()
  {
    ProjectConfiguration::getApplicationConfiguration('front', 'dev', true)->loadHelpers('I18N');
    return $this->getName() ? $this->getName() : __('Guest');
  }
}