<?php

/**
 * Image
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Image extends BaseImage
{
    public function __toString()
    {
        $cul = sfContext::getInstance()->getUser()->getCulture();
        if($cul == 'en')
            return $this->getTitleEn() ? $this->getTitleEn() : $this->getFilename();
        elseif ($cul == 'ru')
            return $this->getTitleRu() ? $this->getTitleRu() : $this->getFilename();
        else 
            return $this->getTitle() ? $this->getTitle() : $this->getFilename();
    }
    
    
    
    public function getDescCulture()
    {
        $cul = sfContext::getInstance()->getUser()->getCulture();
        if($cul == 'en')
            return $this->getDescriptionEn();
        elseif ($cul == 'ru')
            return $this->getDescriptionRu();
        else 
            return $this->getDescription();
    }

}