<?php

/**
 * Partner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Partner extends BasePartner
{
    public function __toString()
    {
      $cul = sfContext::getInstance()->getUser()->getCulture();
      if($cul == 'en')
          return $this->getNameEn();
      elseif ($cul == 'ru')
          return $this->getNameRu();
      else 
          return $this->getName();
    }
    
    
    public function getAddressCulture()
    {
        $cul = sfContext::getInstance()->getUser()->getCulture();
        if($cul == 'en')
            return $this->getAddressEn();
        elseif ($cul == 'ru')
            return $this->getAddressRu();
        else 
            return $this->getAddress();
    }

}