<?php

/**
 * PollOption
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    icoke
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class PollOption extends BasePollOption
{
  public function __toString()
  {	
	     $cul = sfContext::getInstance()->getUser()->getCulture();
        if($cul == 'en')
            return $this->getTextEn();
        elseif ($cul == 'ru')
            return $this->getTextRu();
        else 
            return $this->getText();
	}

}