<?php

/**
 * PollOptionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PollOptionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PollOptionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PollOption');
    }
    
    public static function findByPollId($poll_id)
    {
      $q = Doctrine_Query::create()
             ->from('PollOption')
             ->where('poll_id = ?', $poll_id)
             ->orderBy('sort DESC, text ASC');
      return $q->execute();
    }

  
}