<?php

/**
 * Poll
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    icoke
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Poll extends BasePoll
{
  public function __toString()
  {
  	  $cul = sfContext::getInstance()->getUser()->getCulture();
      if($cul == 'en')
          return $this->getQuestionEn();
      elseif ($cul == 'ru')
          return $this->getQuestionRu();
      else 
          return $this->getQuestion();
	}

	


	public function getOptions()
  {
    $options = Doctrine::getTable('PollOption')->findByPollId($this->getId());

    $options_array = array();
    foreach ($options as $option)
    {
      $options_array[] = '  - '.$option;
    }
    
    return sizeof($options_array) ? join("<br/>", $options_array) : "<i>Сонголт оруулаагүй байна.</i>";
	}
	
	

	

	public function getVotes()
  {
    $options = Doctrine::getTable('PollOption')->findByPollId($this->getId());
    
    $total_number = 0;
    foreach ($options as $option)
    {
      $total_number += $option->getNumber();
    }
    
    
    $votes_array = array();
    foreach ($options as $option)
    {
      $percent = 0;
      if($total_number)
      {
          $percent = $option->getNumber()*100/$total_number;
          $percent = number_format($percent, 1);
      }
      
      $votes_array[$option->getId()] = $option." - <span style='color:#FF7A7F;'>".$option->getNumber()." санал, ".$percent."%</span>";
    }
    
	  return $votes_array;
	}


}