<?php

/**
 * PollTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PollTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PollTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Poll');
    }
    
    
    public static function getPoll()
    {
       $q = Doctrine_Query::create()
             ->from('Poll')
             ->where('id <> 0')
             ->orderBy('sort DESC, created_at DESC, question ASC');
  
       return $q->fetchOne();
    }
  
}