<?php

/**
 * ProductModelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductModelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductModelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductModel');
    }
}