<?php

/**
 * ProductSpecTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductSpecTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductSpecTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductSpec');
    }
}