<?php

/**
 * Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product extends BaseProduct
{
    public function __toString()
    {
          $cul = sfContext::getInstance()->getUser()->getCulture();
          if($cul == 'en')
              return $this->getTitleEn();
          else 
              return $this->getTitle();
    }
    
    public function getSummaryCulture()
    {
        $cul = sfContext::getInstance()->getUser()->getCulture();
        if($cul == 'en')
            return $this->getSummaryEn();
        else 
            return $this->getSummary();
    }
    
    public function getBodyCulture()
    {
        $cul = sfContext::getInstance()->getUser()->getCulture();
        if($cul == 'en')
            return $this->getBodyEn();
        else 
            return $this->getBody();
    }
    
    public function getNbModel()
    {
        return GlobalTable::doCount('ProductModel', array('productId'=>$this->getId()));        
		}
}
