<?php

/**
 * ProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product');
    }
    
    
    public function fetchall($params = array())
    {
        $q = Doctrine_Query::create()
            ->select('*')
            ->from('Product')
            ->orderBy('created_at DESC');
            
            // CATEGORY
            if(isset($params['categoryId']) && $params['categoryId'])
                $q->andWhere('p.category_id = ? ', $params['categoryId']);
  
            // KEYWORD
            if(isset($params['keyword']) && $params['keyword'])
              $q->andWhere('title LIKE ? OR body LIKE ?', array('%'.$params['keyword'].'%', '%'.$params['keyword'].'%'));
  
            // LIMIT
            $limit = isset($params['limit']) ? $params['limit'] : 100;
            $q->limit($limit);
    
        return $q->execute();
    }
    
    
    public function fetcharray($params = array())
    {
        $q = Doctrine_Query::create()
            ->select('p.id, p.title, p.image')
            ->from('Product p')
            ->orderBy('p.created_at DESC');
            
            if(isset($params['orderbyRand']) && $params['orderbyRand']) 
                $q->orderBy('rand()');
                
            // CATEGORY
            if(isset($params['categoryId']) && $params['categoryId'])
                $q->andWhere('p.category_id = ? ', $params['categoryId']);
  
            // KEYWORD
            if(isset($params['keyword']) && $params['keyword'])
                $q->andWhere('p.title LIKE ? OR p.body LIKE ?', array('%'.$params['keyword'].'%', '%'.$params['keyword'].'%'));
  
            // LIMIT
            $limit = isset($params['limit']) ? $params['limit'] : 100;
            $q->limit($limit);
    
        return $q->fetchArray();
    }
  
  
    
    public function getPager($params = array(), $page=1)
    {
        $q = Doctrine_Query::create()
            ->select('*')
            ->from('Product')
            ->orderBy('created_at DESC');
            
            // CATEGORY
            if(isset($params['categoryId']) && $params['categoryId'])
                $q->andWhere('p.category_id = ? ', $params['categoryId']);
  
            // KEYWORD
            if(isset($params['keyword']) && $params['keyword'])
              $q->andWhere('title LIKE ? OR body LIKE ?', array('%'.$params['keyword'].'%', '%'.$params['keyword'].'%'));
  
            // LIMIT
            $limit = isset($params['limit']) ? $params['limit'] : 100;
            $q->limit($limit);
                
        $pager = new sfDoctrinePager('Product', sfConfig::get('app_pager', 30));
        $pager->setPage($page);
        $pager->setQuery($q);
        $pager->init();
        
        return $pager;
    }
}