<?php

/**
 * Service
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    vogue
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Service extends BaseService
{

    public function __toString()
    {
        $cul = sfContext::getInstance()->getUser()->getCulture();
        if($cul == 'en')
            return $this->getTitleEn();
        elseif ($cul == 'ru')
            return $this->getTitleRu();
        else 
            return $this->getTitle();
    }
    
    
    public function getSummaryCulture()
    {
        $cul = sfContext::getInstance()->getUser()->getCulture();
        if($cul == 'en')
            return $this->getSummaryEn();
        elseif ($cul == 'ru')
            return $this->getSummaryRu();
        else 
            return $this->getSummary();
    }
    
    
    public function getBodyCulture()
    {
        $cul = sfContext::getInstance()->getUser()->getCulture();
        if($cul == 'en')
            return $this->getBodyEn();
        elseif ($cul == 'ru')
            return $this->getBodyRu();
        else 
            return $this->getBody();
    }    

}
