<?php

/**
 * SpecTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SpecTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SpecTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Spec');
    }
}