<?php

/**
 * SubscriberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubscriberTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubscriberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Subscriber');
    }
    
    
    public function fetchall($params = array())
    {
        $q = Doctrine_Query::create()
            ->select('*')
            ->from('Subscriber')
            ->orderBy('created_at DESC, s.email ASC');
  
            // KEYWORD
            if(isset($params['keyword']) && $params['keyword'])
              $q->andWhere('title LIKE ? OR body LIKE ?', array('%'.$params['keyword'].'%', '%'.$params['keyword'].'%'));
  
            // LIMIT
            $limit = isset($params['limit']) ? $params['limit'] : 100;
            $q->limit($limit);
    
        return $q->execute();
    }
    
    
    public function getPager($page=1)
    {
        $q = Doctrine_Query::create()
                ->select('*')
                ->from('Subscriber s')
                ->orderBy('s.created_at DESC, s.email ASC');

        $pager = new sfDoctrinePager('Subscriber', sfConfig::get('app_pager', 30));
        $pager->setPage($page);
        $pager->setQuery($q);
        $pager->init();

        return $pager;
    }


}