<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    zzz
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class User extends BaseUser
{
  public function __toString()
  {
      return $this->getFullname() ? $this->getFullname() : ($this->getFirstname() ? $this->getFirstname() : $this->getUsername());
  }

}