# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/07-Databases

all:
  doctrine:
    class: sfDoctrineDatabase
    param:      
      dsn:      mysql:host=mysql8.000webhost.com;dbname=a5625689_simpedi
      username: a5625689_simpedi
      password: a5625689_pwd
      #dsn:      mysql:host=localhost;dbname=simpel6r_2014
      #username: simpel6r_user1
      #password: Password1!
      #dsn:      mysql:host=mysql8.000webhost.com;dbname=a5625689_ny
      #username: a5625689_root
      #password: mongolia$